Repository Samsung/ONE-vscode, pull requests merged in 2022-07, with the labels that each got.

#902 [PartEditor] Revise PartGraphSelector with seleciton
  media/PartEditor/index.js
  src/CircleGraph/CircleGraphCtrl.ts
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#903 [PartEditor] Revise backend combobox
  media/PartEditor/index.js
Labels: 1 approval

#904 [CircleGraph] toggleSelect with ctrl key
  media/CircleGraph/view.js
Labels: 1 approval

#910 [PartEditor] Rename object
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#911 [PartEditor] Show filename as panel title
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#912 [PartEditor] Revise update without backend
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#913 [PartEditor] Forward selection
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#914 [CircleGraph] Add graph node style for backend assignments
  media/CircleGraph/index.js
Labels: 1 approval

#915 [PartEditor] Revise graph node selection
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#905 [OneExplorer] Add run icon inline
  package.json
Labels: 2 approvals, GIF

#917 [PartEditor] Do not check _document
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#916 [PartEditor] Tidy unused member
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#918 [PartEditor] Send partition to Graph
  src/CircleGraph/CircleGraphCtrl.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#919 [CircleGraph] Apply partition for graph nodes
  media/CircleGraph/index.js
  media/CircleGraph/view.js
Labels: 1 approval

#908 [OneExplorer] Save tree root
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#907 [OneExplorer] Add delete command
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals, GIF

#920 [PartGraphSelector] Set node backend assignment after load
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#921 [CircleGraph] Exit forEach after found
  media/CircleGraph/view.js
Labels: 1 approval

#924 [PartEditor] Revise select element usage
  media/PartEditor/index.js
Labels: 1 approval

#925 [CircleGraph] Scroll to selected nodes with flag
  media/CircleGraph/view.js
Labels: 1 approval

#926 [CircleGraph] Comment for view.Node ctor
  media/CircleGraph/view.js
Labels: 1 approval

#927 [CircleGraph] Revise setSelection graph traverse
  media/CircleGraph/view.js
Labels: 1 approval

#837 [DeviceAPI] Add Spec on Backend
  src/Backend/Spec.ts
  src/Tests/Backend/Spec.test.ts
Labels: 2 approvals

#941 [PartEditor] Backend colors when open PartGraphSelector
  src/CircleGraph/BackendColor.ts
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#943 [CircleGraphCtrl] Introduce pageloaded event
  media/CircleGraph/index.js
  src/CircleGraph/CircleGraphCtrl.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#944 [PartEditor] Send backends with color as object
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#945 [CircleGraph] Backend colors from extension
  media/CircleGraph/index.js
  src/CircleGraph/CircleGraphCtrl.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#946 [CircleGraph] setNodeBackend with names from extension
  media/CircleGraph/index.js
  media/CircleGraph/view.js
Labels: 1 approval

#948 [PartEditor] input for find operators
  media/PartEditor/index.css
  media/PartEditor/index.html
Labels: 1 approval

#949 [PartEditor] Find operator with input
  media/PartEditor/index.js
Labels: 1 approval

#954 [PartEditor] Tidy check _document
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#965 [PartEditor] Introduce types for commands
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#967 [PartEditor] Revise cmdOpen with PartGraphCmdOpenArgs
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#969 [PartEditor] Revise cmdUpdate and cmdFwdSelection
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#933 [ToolRunner] Use default value instead of undefined
  src/Project/ToolRunner.ts
Labels: SE

#975 [PartEditor/CircleGraph] Disable context menu
  media/CircleGraph/index.js
  media/PartEditor/index.js
Labels: 1 approval

#974 [PartEditor] Show PartGraphSelector to right of PartEditor
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#982 [CircleGraph] Enable reload message
  media/CircleGraph/index.js
  media/CircleGraph/view.js
Labels: 1 approval

#983 [CircleGraphCtrl] Introduce reloadModel
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#991 [PartEditor] Reset Operators listbox before fill
  media/PartEditor/index.js
Labels: 1 approval

#992 [PartGraphSel] Introduce cmdReload
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#993 [PartEditor] Reload model when changed
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#994 [CircleGraphCtrl] Adjust menu position
  media/CircleGraph/index.html
Labels: 1 approval

#935 [DeviceAPI] Add Device API on Execute
  src/Execute/Device.ts
  src/Tests/Execute/Device.test.ts
Labels: 2 approvals

#978 [OneExplorer] Introduce ArtifactLocator
  src/OneExplorer/ConfigObject.ts
Labels: 2 approvals

#1007 [OneExplorer] Clean and elaborate
  src/OneExplorer/OneExplorer.ts
Labels: 1 approval

#1006 [OneExplorer] Refactor ConfigObject
  src/OneExplorer/ConfigObject.ts
Labels: 2 approvals

#1001 [OneExplorer] Show .circle.log file
  src/OneExplorer/ConfigObject.ts
  src/Tests/OneExplorer/ConfigObject.test.ts
Labels: 2 approvals

#1010 [DeviceAPI] revisit Executor to make this use on Device API
  src/Backend/Executor.ts
  src/Tests/Execute/InferenceQuickInput.test.ts
  src/Tests/Execute/InferenceRunner.test.ts
Labels: 2 approvals

#1012 [Utils] Revisit RealPath
  src/Tests/Utils/Helpers.test.ts
  src/Utils/Helpers.ts
Labels: 2 approvals

#1019 [Execute] Use consistent return statement
  src/Execute/InferenceQuickInput.ts
Labels: 1 approval, SE

#1018 [Tests] Use forEach instead of map
  src/Tests/Execute/InferenceQuickInput.test.ts
Labels: 1 approval, SE

#1024 [Toolchain] Use forEach instead of map
  src/Tests/Toolchain/ToolchainProvider.test.ts
Labels: 1 approval, SE

#1022 [Tests] Use forEach instead of map
  src/Tests/View/InstallQuickInput.test.ts
Labels: 1 approval, SE

#931 [OneExplorer] Refactor OneExplorer
  src/OneExplorer/OneExplorer.ts
  src/extension.ts
Labels: SE

#1014 [Backend] Add registerExecutor API on backend register
  src/Backend/Backend.ts
  src/Tests/Backend/Backend.test.ts
Labels: 2 approvals

#1016 [OneExplorer] Rewrite ConfigObject
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/OneExplorer.ts
  src/Tests/OneExplorer/ConfigObject.test.ts
Labels: 1 approval

#1020 [OneExplorer] Rewrite OneExplorer
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/OneExplorer.ts
Labels: 1 approval, Ready for review

#1032 Deprecate --O1 option
  media/CfgEditor/one-optimizations.json
  src/Project/BuilderCfgFile.ts
  src/Project/JobOptimize.ts
  src/Tests/Project/JobOptimize.test.ts
Labels: 2 approvals

#1017 [CircleGraph] Use consistent return statement
  src/CircleGraph/CircleViewer.ts
Labels: 1 approval, SE

#1023 [PartEditor] Use consistent return statement
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval, SE

#1033 [CircleGraph] Remove no-effect return statement
  media/CircleGraph/view.js
Labels: 1 approval, SE

#1034 [CircleGraph] Remove no-effect return statement
  media/CircleGraph/view.js
Labels: 1 approval, SE

#1038 [OneExplorer] Rename DerivedModel to Product
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/OneExplorer.ts
  src/Tests/OneExplorer/ConfigObject.test.ts
Labels: 1 approval

#1040 [PartEditor] Exclude properties from the prototype
  media/PartEditor/index.js
Labels: 1 approval, SE

#1025 [Mondrian] Declare variable with const
  media/Mondrian/mondrianViewer.js
Labels: 1 approval, SE

#1031 [OneExplorer] Do not use useless return
  src/OneExplorer/OneExplorer.ts
Labels: 1 approval, SE

#1013 [OneExplorer] Handle no workspace opened case
  src/OneExplorer/OneExplorer.ts
Labels: Ready for review

#1041 [OneExplorer] Refactor with abstract class
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1044 [OneExplorer] Change model file icon
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals, Ready for review

#1054 [OneExplorer] Integrate same if-else statement
  src/OneExplorer/OneExplorer.ts
Labels: 1 approval, SE

#1056 Update .gitignore for coverage test
  .gitignore
Labels: 2 approvals

#1058 [OneExplorer] Fix parsing ConfigObj
  src/OneExplorer/ConfigObject.ts
Labels: 2 approvals, Ready for review

#1060 Update .gitignore for test result
  .gitignore
Labels: 1 approval

#1066 [CircleGraph] Extract handleChangeConfiguration
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#1067 [CircleGraph] Revise createOrShow to return panel object
  src/CircleGraph/CircleGraph.ts
Labels: 1 approval

#1059 [OneExplorer] Show chrome trace files
  src/OneExplorer/ConfigObject.ts
Labels: 2 approvals, Ready for review

#1072 [res] Sample circle model for unit testing
  res/samples/circle/test_onnx.circle
Labels: 1 approval

#1062 [OneExplorer] Separate ArtifactLocator.ts
  src/OneExplorer/ArtifactLocator.ts
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1073 [OneExplorer] Fix bug of duplicated root
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1074 [OneExplorer] Throw non-absolute path from LocatorRunner
  src/OneExplorer/ArtifactLocator.ts
Labels: 1 approval

#1050 [Backend] Exchange the file names: API, Backend
  src/Backend/API.ts
  src/Backend/Backend.ts
  src/Execute/InferenceQuickInput.ts
  src/Execute/InferenceRunner.ts
  src/Tests/Backend/Backend.test.ts
  src/Tests/Execute/InferenceQuickInput.test.ts
  src/Tests/Execute/InferenceRunner.test.ts
  src/extension.ts
Labels: 2 approvals, Ready for review

#1077 [CircleGraph] Use consistent return statement
  src/CircleGraph/CircleGraph.ts
Labels: 1 approval, SE

#1045 [DeviceAPI] Add ExecutionManager
  src/Execute/Device.ts
  src/Execute/DeviceManager.ts
  src/Tests/Execute/DeviceManager.test.ts
Labels: 2 approvals

#1075 [CircleGraph/test] Initial test for CircleGraphPanel
  src/Tests/CircleGraph/CircleGraph.test.ts
Labels: 2 approvals

#1079 [OneExplorer] Add assertions on ArtifactLocator
  src/OneExplorer/ArtifactLocator.ts
Labels: 2 approvals

#1082 [CircleGraph] Exclude UI related codes from coverage analysis
  src/CircleGraph/CircleGraph.ts
  src/CircleGraph/CircleGraphCtrl.ts
  src/CircleGraph/CircleViewer.ts
Labels: 1 approval, SE

#1086 [CfgEditor] Exclude UI related codes from coverage analysis
  src/CfgEditor/CfgEditorPanel.ts
Labels: 1 approval, SE

#1064 [OneExplorer] Add ArtifactLocator unit tests
  src/Tests/OneExplorer/ArtifactLocator.test.ts
Labels: 2 approvals

#1069 [OneExplorer] Use default value for function parameter
  src/OneExplorer/OneExplorer.ts
Labels: 1 approval, SE

#1083 [OneExplorer] Exclude UI related codes from coverage analysis
  src/OneExplorer/OneExplorer.ts
  src/OneExplorer/OneccRunner.ts
Labels: 1 approval, SE

#1085 [Execute] Exclude UI related codes from coverage analysis
  src/Execute/InferenceShowBox.ts
Labels: 1 approval, SE

#1087 Exclude external open source from coverage analysis
  package.json
Labels: 1 approval, SE

#1097 [Backend] Add `executors()` API on `Backend`.
  src/Backend/Backend.ts
  src/Tests/Backend/Backend.test.ts
  src/Tests/Execute/InferenceQuickInput.test.ts
  src/Tests/Execute/InferenceRunner.test.ts
Labels: 2 approvals

#1084 [Mondrian] Exclude UI related codes from coverage analysis
  src/Mondrian/MondrianEditor.ts
Labels: 1 approval, SE

#1037 [Spec] revisit sdbSpec
  script/sdbSpecList.sh
  src/Backend/Spec.ts
  src/Tests/Backend/Spec.test.ts
Labels: 2 approvals, Ready for review

#1100 [OneExplorer] Show .tv2* files
  src/OneExplorer/ConfigObject.ts
Labels: 2 approvals, GIF

#1043 Provide welcome guide via ONE view container
  package.json
Labels: 2 approvals

#1102 [OneExplorer] Add ConfigObject unit tests
  src/Tests/OneExplorer/ConfigObject.test.ts
Labels: 2 approvals

#1101 Refresh toolchain View after backend registraion
  src/Backend/API.ts
Labels: 2 approvals

#1111 [Jsontracer] Fix static analysis warnings
  media/Jsontracer/bar.js
  media/Jsontracer/calculateGraduation.js
  media/Jsontracer/dashboard.js
  media/Jsontracer/detail.js
  media/Jsontracer/level.js
Labels: 1 approval, SE

#1092 [DeviceView] Add DeviceView Provider
  package.json
  script/sdbSpecList.sh
  src/Backend/API.ts
  src/Execute/DeviceViewProvider.ts
  src/Tests/Execute/DeviceViewProvider.test.ts
  src/extension.ts
Labels: 2 approvals
