Repository Samsung/ONE-vscode, pull requests merged in 2022-11, with the labels that each got.

#1438 [OneExplorer] Add id to Node
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1439 [OneExplorer] Revisit NodeFactory.create
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1440 [OneExplorer] Move _nodeMap to OneStorage
  src/OneExplorer/OneExplorer.ts
  src/OneExplorer/OneStorage.ts
Labels: 2 approvals

#1437 [OneExplorer] Use vscode.WorkspaceEdit
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1444 [Test] Use TestBuilder
  src/Tests/OneExplorer/ConfigObject.test.ts
  src/Tests/OneExplorer/OneStorage.test.ts
Labels: 2 approvals, Ready for review

#1449 [OneStorage] Clarify ConfigObjMaps value
  src/OneExplorer/OneStorage.ts
Labels: 1 approval

#1450 [OneStorage/test] Rearrange suites
  src/Tests/OneExplorer/OneStorage.test.ts
Labels: 1 approval

#1448 [OneStorage] Rename function
  src/OneExplorer/OneStorage.ts
Labels: 1 approval

#1451 [OneExplorer] Fix comment
  src/OneExplorer/ArtifactLocator.ts
Labels: 1 approval

#1452 [OneExplorer/Test] Clarify tests
  src/Tests/OneExplorer/ConfigObject.test.ts
  src/Tests/OneExplorer/OneExplorer.test.ts
  src/Tests/OneExplorer/OneStorage.test.ts
Labels: 2 approvals

#1453 [OneExplorer] Introduce BaseModelToCfgMap/CfgToCfgObjMap
  src/OneExplorer/OneStorage.ts
  src/Tests/OneExplorer/OneStorage.test.ts
Labels: 2 approvals

#1456 [One Explorer] Set default value for delete function
  src/OneExplorer/OneStorage.ts
Labels: 1 approval, SE
