Repository Samsung/ONE-vscode, pull requests merged in 2022-08, with the labels that each got.

#1103 [OneExplorer] Introduce hide command and button
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals, GIF

#1119 [PartEditor] Exclude UI related codes from coverage analysis
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval, SE

#1121 [OneExplorer] Reorder context menus
  package.json
Labels: 2 approvals

#1125 [CircleGraph] Use external source code instead of modified source code
  media/CircleGraph/view-sidebar.js
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval, SE

#1124 [OneExplorer] Show tracealloc.json files
  src/OneExplorer/ConfigObject.ts
  src/Tests/OneExplorer/ConfigObject.test.ts
Labels: 2 approvals

#1130 [Backend] Add dummy toolchain unit tests
  src/Tests/Backend/Toolchain.test.ts
Labels: 2 approvals

#1133 [OneExplorer] Change some warning logs
  src/OneExplorer/ConfigObject.ts
Labels: 1 approval

#1128 [Backend] Add dummy CompilerBase unit tests
  src/Tests/Backend/Compiler.test.ts
Labels: 2 approvals

#1129 [Backend] Add dummy ExecutorBase unit tests
  src/Tests/Backend/Executor.test.ts
Labels: 2 approvals

#1140 [Job] Add context related to job running status
  package.json
  src/Job/JobRunner.ts
Labels: 2 approvals

#1147 [Jsontracer] Exclude UI related codes from coverage analysis
  src/Jsontracer.ts
  src/Jsontracer/GetWebviewOptions.ts
Labels: 1 approval, SE

#1141 [OneExplorer] Open *.circle files with circleViewer
  src/OneExplorer/ConfigObject.ts
Labels: 2 approvals

#1139 [DeviceView] Fix Device Executor display bug
  src/Execute/DeviceViewProvider.ts
Labels: 2 approvals

#1146 Initialize Test Case Administrator with fixing some TCs
  .ahub/tcchecker-tca/config.yaml
  src/Tests/Backend/Compiler.test.ts
  src/Tests/Backend/Executor.test.ts
  src/Tests/Backend/Toolchain.test.ts
  src/Tests/Backend/ToolchainImpl/DebianToolchain.test.ts
  src/Tests/CfgEditor/CfgData.test.ts
  src/Tests/Execute/DeviceViewProvider.test.ts
  src/Tests/OneExplorer/ConfigObject.test.ts
  src/Tests/Toolchain/ToolchainProvider.test.ts
  src/Tests/Utils/Helpers.test.ts
Labels: SE

#1149 Exclude UI related codes from coverage analysis
  src/extension.ts
Labels: 1 approval, SE

#1137 [TEST] add NEG test case for Device
  src/Execute/Device.ts
  src/Tests/Execute/Device.test.ts
Labels: 2 approvals

#1152 [CfgEditor] Remove HtmlBuilder
  src/CfgEditor/CfgEditorPanel.ts
  src/CfgEditor/CfgHtmlBuilder.ts
  src/Tests/CfgEditor/CfgHtmlBuilder.test.ts
Labels: 1 approval, SE

#1150 [TEST] Add Test on `Workflow.test.ts`
  src/Tests/Job/Workflow.test.ts
Labels: 2 approvals

#1161 [Toolchain] Use Toolchain suite name
  src/Tests/Toolchain/JobConfig.test.ts
  src/Tests/Toolchain/JobInstall.test.ts
  src/Tests/Toolchain/JobUninstall.test.ts
Labels: 1 approval

#1153 [Backend] Add more testcases for Version
  src/Tests/Backend/Version.test.ts
Labels: 1 approval, SE

#1155 [View] Revise unit tests
  src/Tests/View/InstallQuickInput.test.ts
  src/Tests/View/PasswordQuickInput.test.ts
  src/View/InstallQuickInput.ts
  src/View/PasswordQuickInput.ts
Labels: 1 approval, SE

#1162 [CircleGraph] Remove testcases
  src/Tests/CircleGraph/CircleGraph.test.ts
Labels: 1 approval, SE

#1173 [CfgEditor] Tidy registration
  src/CfgEditor/CfgEditorPanel.ts
  src/extension.ts
Labels: 1 approval

#1132 [TEST] revisit DeviceViewProvider test
  src/Execute/DeviceViewProvider.ts
  src/Tests/Execute/DeviceViewProvider.test.ts
Labels: 1 approval, SE

#1154 [Utils] Improve line and function coverage
  src/Tests/Utils/Helpers.test.ts
  src/Utils/Helpers.ts
Labels: 1 approval, SE

#1177 [View] Add negative tests and break down test
  src/Tests/View/InstallQuickInput.test.ts
Labels: 1 approval

#1170 [Toolchain] Tidy registration
  src/Toolchain/ToolchainProvider.ts
  src/extension.ts
Labels: 2 approvals

#1171 [Device] Tidy registration
  src/Execute/DeviceViewProvider.ts
  src/extension.ts
Labels: 2 approvals

#1181 [CircleViewer] Tidy registration
  src/CircleGraph/CircleViewer.ts
  src/extension.ts
Labels: 1 approval

#1179 [Tests] Fix trivial mistakes
  src/Tests/Backend/Command.test.ts
  src/Tests/Backend/Compiler.test.ts
  src/Tests/Backend/Executor.test.ts
  src/Tests/Backend/Spec.test.ts
  src/Tests/Backend/Toolchain.test.ts
  src/Tests/Backend/ToolchainImpl/DebianToolchain.test.ts
  src/Tests/Backend/Version.test.ts
  src/Tests/Execute/Device.test.ts
  src/Tests/Job/Workflow.test.ts
  src/Tests/Toolchain/JobConfig.test.ts
  src/Tests/Toolchain/JobInstall.test.ts
  src/Tests/Toolchain/JobPrerequisites.test.ts
  src/Tests/Toolchain/JobUninstall.test.ts
Labels: 1 approval

#1168 [OneExplorer] Tidy registration
  src/OneExplorer/OneExplorer.ts
  src/extension.ts
Labels: 2 approvals

#1180 [PartEditor] Tidy registration
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
  src/extension.ts
Labels: 2 approvals

#1186 [View] Add more negative TCs for InstallQuickInput
  src/Tests/View/InstallQuickInput.test.ts
Labels: 1 approval

#1178 [Mondrian] Tidy registration
  src/Mondrian/MondrianEditor.ts
  src/extension.ts
Labels: 1 approval

#1166 Format custom editor view types
  package.json
  src/CfgEditor/CfgEditorPanel.ts
  src/CircleGraph/CircleViewer.ts
  src/Jsontracer.ts
  src/Mondrian/MondrianEditor.ts
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/OneExplorer.ts
  src/PartEditor/PartEditor.ts
  src/extension.ts
Labels: 2 approvals

#1189 [Utils] Change test to negative test
  src/Tests/Utils/Helpers.test.ts
Labels: 1 approval

#1190 [OneExplorer] Show chrome trace files
  src/OneExplorer/ConfigObject.ts
Labels: 2 approvals, GIF

#1195 [Tests] Fix trivial errors
  src/Tests/Toolchain/ToolchainEnv.test.ts
  src/Tests/View/InstallQuickInput.test.ts
Labels: 1 approval

#1131 [OneExplorer] Add OneNode unit tests
  src/OneExplorer/OneExplorer.ts
  src/Tests/OneExplorer/OneExplorer.test.ts
Labels: 2 approvals

#1142 [DeviceView] Fix `DeviceView` Error case for `command not found`
  script/sdbSpecList.sh
  src/Execute/DeviceViewProvider.ts
Labels: 2 approvals

#1197 [Tests/Utils] Add a negative TC
  src/Tests/Utils/PipedSpawn.test.ts
Labels: 1 approval

#1196 [Tests/Utils] Revise test cases
  src/Tests/Utils/Helpers.test.ts
  src/Utils/Helpers.ts
Labels: 1 approval

#1202 [Tests/View] Add more test cases
  src/Tests/View/InstallQuickInput.test.ts
Labels: 1 approval

#1203 [Tests/Utils] Add more test cases
  src/Tests/Utils/Helpers.test.ts
Labels: 1 approval

#1208 [OneExplorer] Fix the bug of not showing trace result immediately
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals, Quick Fix

#1207 [OneExplorer] Fix the bug of delete command in ssh-remote env
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals, Quick Fix

#1188 [Infra] Add Release Note for ONE-vscode v0.3.0
  infra/release/release_note.md
Labels: release

#1211 [res] Add sample file for Jsontracer
  res/samples/traces/sample.timeline.json
Labels: 1 approval

#1193 Update Version to 0.3.0
  package-lock.json
  package.json
Labels: release

#1220 [OneExplorer] Use extensionKind to know whether extensions' remote
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1219 [OneExplorer] Refresh on directory deletion/move
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1221 [OneExplorer] Disable openContainingDirectory based on extensionKind
  package.json
  src/OneExplorer/OneExplorer.ts
  src/extension.ts
Labels: 2 approvals

#1225 [JsonTracer] Add `displayTimeUnit` to DOM
  media/Jsontracer/index.js
  media/Jsontracer/processData.js
  src/Jsontracer/JsonTracerViewerPanel.ts
Labels: 2 approvals

#1230 Fix package.json
  package.json
Labels: 1 approval

#1227 [OneExplorer] Introduce OneStorage to improve latency
  src/OneExplorer/OneExplorer.ts
  src/OneExplorer/OneStorage.ts
Labels: 2 approvals, GIF

#1235 [OneExplorer] Add 'Reveal in explorer view' command
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals, GIF

#1237 [OneExplorer] Deprecate OneccRunner.ts
  src/OneExplorer/OneccRunner.ts
Labels: 2 approvals

#1231 [OneExplorer] Add OneStorage unit tests
  src/OneExplorer/OneStorage.ts
  src/Tests/OneExplorer/OneStorage.test.ts
Labels: 2 approvals

#1243 [OneExplorer] Deprecate rename command
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1245 [OneExplorer] Subscribe filewatcher events
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals
