Repository Samsung/ONE-vscode, pull requests merged in 2022-09, with the labels that each got.

#1248 [OneExplorer] Do not build hidden nodes
  src/OneExplorer/OneExplorer.ts
  src/Tests/OneExplorer/OneExplorer.test.ts
Labels: 2 approvals

#1249 [OneExplorer] Build children on demand
  src/OneExplorer/OneExplorer.ts
  src/Tests/OneExplorer/OneExplorer.test.ts
Labels: 2 approvals

#1251 [OneExplorer] Change element type to Node from OneNode
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1254 [lint] Remove unnecessary semicolons
  .eslintrc.json
  media/PartEditor/index.js
  src/Backend/Command.ts
  src/Backend/Compiler.ts
  src/Backend/Executor.ts
  src/Backend/Toolchain.ts
  src/Backend/ToolchainImpl/DebianToolchain.ts
  src/Backend/Version.ts
  src/CfgEditor/CfgEditorPanel.ts
  src/CircleGraph/CircleGraphCtrl.ts
  src/CircleGraph/CircleViewer.ts
  src/Jsontracer/JsonTracerViewerPanel.ts
  src/OneExplorer/ArtifactLocator.ts
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/OneExplorer.ts
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
  src/Tests/OneExplorer/ConfigObject.test.ts
  src/Tests/OneExplorer/OneExplorer.test.ts
  src/Tests/OneExplorer/OneStorage.test.ts
Labels: 2 approvals

#1238 [ToolchainProvider] Ask user to save documents before run
  src/Tests/Toolchain/ToolchainProvider.test.ts
  src/Toolchain/ToolchainProvider.ts
  src/Utils/Helpers.ts
Labels: 2 approvals, Ready for review

#1255 [lint] Add envs and globals
  .eslintrc.json
Labels: 2 approvals

#1256 [lint] Remove no-case-declarations
  .eslintrc.json
  src/CfgEditor/CfgEditorPanel.ts
Labels: 2 approvals

#1257 [lint] Remove no-useless-escape
  .eslintrc.json
  src/CircleGraph/CircleGraphCtrl.ts
  src/PartEditor/PartEditor.ts
Labels: 2 approvals

#1259 [lint] Remove no-prototype-builtins
  .eslintrc.json
  media/CircleGraph/view.js
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 2 approvals

#1258 [lint] Remove no-control-regex
  .eslintrc.json
  src/View/PasswordQuickInput.ts
Labels: 2 approvals

#1262 [res] Add example circle file
  res/samples/circle/while_000.circle
Labels: 1 approval

#1263 [OneExplorer] Add parent to Node
  src/OneExplorer/OneExplorer.ts
  src/Tests/OneExplorer/OneExplorer.test.ts
Labels: 2 approvals

#1264 [OneExplorer] Reveal focused cfg file in OneExplorer
  package.json
  src/CfgEditor/CfgEditorPanel.ts
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals, GIF

#1267 [lint] Remove unused variables from Toolchain
  src/Backend/Toolchain.ts
  src/Toolchain/DefaultToolchain.ts
  src/Toolchain/ToolchainEnv.ts
Labels: 2 approvals

#1273 [lint] Remove some unused variables
  src/CfgEditor/CfgEditorPanel.ts
  src/Execute/DeviceViewProvider.ts
  src/Job/ToolRunner.ts
  src/Jsontracer/JsonTracerViewerPanel.ts
  src/View/InstallQuickInput.ts
Labels: 2 approvals

#1268 [lint] Remove unused variables from CircleGraph and PartEditor
  src/CircleGraph/CircleGraph.ts
  src/CircleGraph/CircleGraphCtrl.ts
  src/CircleGraph/CircleViewer.ts
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 2 approvals

#1289 [ONEToolchain] Introduce ONEToolchain
  src/Backend/API.ts
  src/Backend/ONE/ONEToolchain.ts
  src/Tests/Backend/Backend.test.ts
  src/Tests/Backend/ONE/ONEToolchain.test.ts
  src/Tests/Toolchain/ToolchainProvider.test.ts
  src/Tests/View/InstallQuickInput.test.ts
Labels: Ready for review, SSAFY

#1274 [lint] Remove unused generics from MultiStepInput
  src/Utils/MultiStepInput.ts
Labels: 1 approval

#1300 [lint] Remove unused variables from .js files
  media/CircleGraph/index.js
  media/CircleGraph/view.js
  media/Mondrian/mondrianViewer.js
  media/PartEditor/index.js
Labels: 2 approvals

#1301 [OneExplorer] Revisit OneExplorer Unit Tests
  src/Tests/OneExplorer/OneStorage.test.ts
Labels: 2 approvals

#1299 [lint] Add no-unused-vars rule
  .eslintrc.json
Labels: 2 approvals

#1302 [lint] Remove re-declare
  src/Job/Job.ts
  src/Job/JobCommand.ts
  src/Tests/MockJob.ts
  src/Tests/Toolchain/JobConfig.test.ts
  src/Tests/Toolchain/JobInstall.test.ts
  src/Tests/Toolchain/JobPrerequisites.test.ts
  src/Tests/Toolchain/JobUninstall.test.ts
  src/Toolchain/JobConfig.ts
  src/Toolchain/JobInstall.ts
  src/Toolchain/JobPrerequisites.ts
  src/Toolchain/JobUninstall.ts
Labels: 2 approvals

#1307 [CircleEditor] Add files for making Circle model object
  .eslintignore
  infra/license/package-judgment.json
  package-lock.json
  package.json
  src/CircleEditor/CircleType.ts
  src/CircleEditor/circle_schema_generated.ts
Labels: SSAFY

#1308 [CircleEditor] Introduce CircleEditor
  .eslintignore
  infra/copyright/copyright-checker.ts
  media/CircleEditor/.clang-format
  media/CircleEditor/README.md
  media/CircleEditor/circle-metadata.json
  media/CircleEditor/external/.FORMATDENY
  media/CircleEditor/external/LICENSE
  media/CircleEditor/external/ORIGIN
  media/CircleEditor/external/base.js
  media/CircleEditor/external/circle-schema.js
  media/CircleEditor/external/circle.js
  media/CircleEditor/external/dagre.js
  media/CircleEditor/external/flatbuffers.js
  media/CircleEditor/external/flexbuffers.js
  media/CircleEditor/external/gzip.js
  media/CircleEditor/external/json.js
  media/CircleEditor/external/protobuf.js
  media/CircleEditor/external/python.js
  media/CircleEditor/external/tar.js
  media/CircleEditor/external/text.js
  media/CircleEditor/external/xml.js
  media/CircleEditor/external/zip.js
  media/CircleEditor/index.html
  media/CircleEditor/index.js
  media/CircleEditor/type.js
  media/CircleEditor/view-grapher.css
  media/CircleEditor/view-grapher.js
  media/CircleEditor/view-sidebar.css
  media/CircleEditor/view-sidebar.js
  media/CircleEditor/view.js
Labels: SSAFY
