Repository Samsung/ONE-vscode, pull requests merged in 2022-10, with the labels that each got.

#1309 [lint] Use eslint:recommended
  .eslintrc.json
Labels: 2 approvals

#1311 [docs] Update docs/Tutorial.md
  docs/OneToolchain.jpg
  docs/Tutorial.md
Labels: Ready for review, SSAFY

#1321 [Utils] Introduce Hash.ts
  src/Utils/Hash.ts
Labels: 2 approvals, SSAFY

#1326 [CircleGraph] Fix to find file system path
  src/CircleGraph/CircleViewer.ts
Labels: 1 approval

#1323 [Test] Introduce TestBuilder
  src/Tests/OneExplorer/OneExplorer.test.ts
  src/Tests/TestBuilder.ts
Labels: 2 approvals

#1295 [ONEToolchain] Implement compiler of ONEToolchain
  script/prerequisitesForGetToolchains.sh
  src/Backend/One/OneToolchain.ts
  src/Tests/Backend/One/OneToolchain.test.ts
Labels: Ready for review, SSAFY

#1317 [CircleEditor] Preprocessing for Editing Circle Files
  media/CircleEditor/index.js
  media/CircleEditor/view.js
Labels: SSAFY

#1313 [Metadata Manager] Introduce Metadata Event Manager
  src/MetadataManager/MetadataEventManager.ts
  src/MetadataManager/README.md
Labels: 2 approvals, Ready for review, SSAFY

#1315 [MetadataViewer] Introduce Metadata Viewer
  media/MetadataViewer/index.html
  media/MetadataViewer/index.js
  media/MetadataViewer/style.css
  package.json
  src/MetadataViewer/MetadataViewer.ts
  src/MetadataViewer/MetadataViewerProvider.ts
  src/MetadataViewer/example/MetadataExample.ts
  src/extension.ts
Labels: 2 approvals, Ready for review, GIF, SSAFY

#1328 [CircleEditor] Adds files for activating circle custom editor
  package.json
  src/CircleEditor/CircleEditorDocument.ts
  src/CircleEditor/CircleEditorProvider.ts
  src/Utils/external/Dispose.ts
  src/extension.ts
Labels: SSAFY

#1340 [CircleEditor] Add codicon
  media/CircleEditor/index.html
Labels: 1 approval

#1341 [CircleEditor] Add Attributes Edit function
  media/CircleEditor/type.js
  media/CircleEditor/view-sidebar.js
Labels: SSAFY

#1327 [Test] Add unit test for isTargetFile
  src/Tests/Utils/Helpers.test.ts
Labels: 2 approvals, SSAFY

#1344 [CircleEditor] Add Json editor feature
  src/CircleEditor/CircleEditorDocument.ts
  src/CircleEditor/CircleEditorProvider.ts
Labels: SSAFY

#1324 [Test] Add unit test for Hash.ts
  src/Tests/Utils/Hash.test.ts
Labels: 2 approvals

#1346 [CircleEditor] Add CustomOp name edit function
  media/CircleEditor/view-sidebar.js
Labels: SSAFY

#1342 [CircleEditor] Add edit & send logic.
  src/CircleEditor/CircleEditorDocument.ts
  src/CircleEditor/CircleEditorProvider.ts
  src/CircleEditor/CircleType.ts
Labels: SSAFY

#1347 [CircleEditor] Add Input and Output Edit Function
  media/CircleEditor/view-sidebar.js
Labels: SSAFY

#1354 [CircleGraphCtrl] Remove unused message command
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#1355 [Tests/Utils] Add missing assert
  src/Tests/Utils/Hash.test.ts
Labels: 1 approval

#1353 [CircleGraphCtrl] Relocate handlers
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#1356 [media/CircleGraph] Introduce region for legend
  media/CircleGraph/index.html
Labels: 2 approvals

#1357 [visq] Introduce initial VisqProvider
  src/VisqProvider/VisqViewer.ts
  src/extension.ts
Labels: 2 approvals

#1358 [CircleGraphCtrl] Introduce onViewMessage and revise
  src/CircleGraph/CircleGraphCtrl.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 2 approvals

#1362 [CircleGraphCtrl] Tidy unused with CircleGraphEvent
  src/CircleGraph/CircleGraphCtrl.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 2 approvals

#1363 [CircleGraphCtrl] Relocate loadContent
  src/CircleGraph/CircleGraph.ts
  src/CircleGraph/CircleGraphCtrl.ts
  src/CircleGraph/CircleViewer.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#1360 [OneExplorer] Revive rename command
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals, GIF

#1364 [media/CircleGraph] Introduce visq mode
  media/CircleGraph/index.js
  media/CircleGraph/view.js
Labels: 2 approvals

#1365 [CircleGraphCtrl] Add notes for received messages
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#1370 [MetadataManager] Return consistent type
  src/MetadataManager/Metadata.ts
Labels: 1 approval, SE

#1368 [media/CircleGraph] Comment for viewMode
  media/CircleGraph/index.js
Labels: 2 approvals

#1369 [Utils] Fix wrong return type for filter function
  src/Utils/Helpers.ts
Labels: 1 approval, SE

#1366 [VisqProvider] Load visq.json
  src/VisqProvider/VisqViewer.ts
Labels: 2 approvals

#1374 [visq] Use path.join
  src/VisqProvider/VisqViewer.ts
Labels: 1 approval

#1372 [media/CirGr] Start with visq command
  media/CircleGraph/index.js
Labels: 2 approvals

#1375 [visq] Revise VisqViewer to handle visq message
  src/CircleGraph/CircleGraphCtrl.ts
  src/VisqProvider/VisqViewer.ts
Labels: 2 approvals

#1376 [media/CircleGraph] Handle visq message
  media/CircleGraph/index.js
Labels: 2 approvals

#1377 [visquv] Rename folder to visquv
  src/Visquv/VisqViewer.ts
  src/extension.ts
Labels: 2 approvals

#1378 [CircleEditor] Classify EditInputsOutputsView
  media/CircleEditor/view-sidebar.js
Labels: SSAFY

#1380 Register visq viewer
  package.json
Labels: 2 approvals

#1314 [MetaProvider] Introduce PathToHash
  src/MetadataManager/PathToHash.ts
Labels: 2 approvals, SSAFY

#1379 [media/CircleGraph] Implement visq settings method
  media/CircleGraph/index.js
Labels: 2 approvals

#1381 [OneExplorer] Allow rename command only for config files
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1384 [media/CircleGraph] Apply visq value and color
  media/CircleGraph/index.js
  media/CircleGraph/view.js
Labels: 2 approvals

#1388 [OneExplorer] Revisit rename command
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1389 [CircleEditor] Add external directory to excluding list
  .ahub/sam/exclude.txt
Labels: 1 approval

#1367 [MetadataViewer] Filter properties in for-in loop
  media/MetadataViewer/index.js
Labels: 1 approval, SE

#1393 [MetadataManager] Fix incorrect return type for callback function
  src/MetadataManager/PathToHash.ts
Labels: 1 approval, SE

#1394 [CircleGraph] Filter properties in for-in loop
  media/CircleGraph/index.js
Labels: 1 approval, SE

#1395 [media/CircleGraph] Introduce visqMetric
  media/CircleGraph/index.js
Labels: 2 approvals

#1361 [OneExplorer] Support refactoring by renaming
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals, Ready for review, GIF

#1396 [CircleViewer] Enable reload when changed
  src/CircleGraph/CircleViewer.ts
Labels: 2 approvals

#1400 [CircleViewer] Comment for reload delay
  src/CircleGraph/CircleViewer.ts
Labels: 1 approval

#1398 [media/CircleGraph] Set visq attributes into node
  media/CircleGraph/view.js
Labels: 2 approvals

#1404 [media/CircleGraph] Tidy comment
  media/CircleGraph/view.js
Labels: 1 approval

#1397 [CircleGraph] Prepare view-sidebar.js
  media/CircleGraph/view-sidebar.js
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 2 approvals

#1403 [OneExplorer] Build a node map on demand
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1406 [media/CircleGraph] Revise visq style
  media/CircleGraph/index.js
Labels: 1 approval

#1410 [media/CircleGraph] Style title for visquv
  media/CircleGraph/index.js
Labels: 1 approval

#1407 [media/CircleGraph] Add property field for visq metric
  media/CircleGraph/view-sidebar.js
Labels: 2 approvals

#1411 [media/CircleGraph] Visquv export style
  media/CircleGraph/view.js
Labels: 2 approvals

#1412 [media/CircleGraph] Revise blob export
  media/CircleGraph/index.js
Labels: 2 approvals

#1405 [OneExplorer] Return consistent return type
  src/OneExplorer/OneExplorer.ts
Labels: 1 approval, SE

#1414 [media/CircleGraph] Add export menu for visquv
  media/CircleGraph/index.js
Labels: 2 approvals

#1413 [Visquv] Introduce export file
  src/CircleGraph/CircleGraphCtrl.ts
  src/Visquv/VisqViewer.ts
Labels: 2 approvals

#1415 [OneExplorer] Revisit OneStorage
  src/OneExplorer/OneStorage.ts
Labels: 1 approval

#1418 [OneExplorer] Remove unused getCfgList()
  src/OneExplorer/OneExplorer.ts
  src/OneExplorer/OneStorage.ts
  src/Tests/OneExplorer/OneExplorer.test.ts
Labels: 1 approval

#1416 [OneExplorer] Revise Refresh to re-build only the changed node
  src/OneExplorer/OneExplorer.ts
  src/OneExplorer/OneStorage.ts
Labels: 2 approvals, GIF

#1420 [Helpers] Fix obtainWorkspaceRoot
  src/Utils/Helpers.ts
Labels: 2 approvals

#1423 [visquv] Extract common method makeModelPath
  src/Visquv/VisqViewer.ts
Labels: 1 approval

#1421 [OneExplorer] Simplify getting workspaceRoot
  src/OneExplorer/OneExplorer.ts
  src/Utils/Helpers.ts
Labels: 2 approvals

#1424 [Utils] Introduce obtainWorkspaceRoots
  src/Utils/Helpers.ts
Labels: 2 approvals

#1419 [OneExplorer] Support multi-root workspaces
  src/OneExplorer/OneExplorer.ts
  src/OneExplorer/OneStorage.ts
Labels: Ready for review, GIF

#1426 [OneExplorer] Show full path in description
  src/OneExplorer/OneExplorer.ts
  src/Tests/OneExplorer/OneExplorer.test.ts
Labels: 2 approvals, Ready for review

#1430 [OneExplorer] Remove redundant refresh
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1432 [CI] Use pull_request instead of pull_request_target
  .github/workflows/check-commit.yml
  .github/workflows/check-copyright.yml
  .github/workflows/check-license.yml
Labels: 2 approvals

#1433 [CI] Make CI fail when license verification is failed
  .github/workflows/check-license.yml
Labels: 2 approvals

#1434 [OneExplorer] Subscribe omitted disposables
  src/OneExplorer/OneExplorer.ts
Labels: 1 approval

#1435 [OneExplorer] Optimize Hide&Show
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1441 [OneExplorer] Use chai instead of assert
  src/OneExplorer/OneExplorer.ts
Labels: 1 approval
