Repository Samsung/ONE-vscode, pull requests merged in 2022-06, with the labels that each got.

#745 [OneExplorer] Improve Create Cfg UI
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#724 [Toolchain] Refresh toolchain list
  src/Project/Job.ts
  src/Project/JobPrerequisites.ts
  src/Toolchain/ToolchainEnv.ts
  src/View/InstallQuickInput.ts
Labels: Ready for review

#747 [OneExplorer] Show and open config on create
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals, GIF

#743 [PartEditor] Revise backend list from extension
  media/PartEditor/index.html
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 2 approvals

#703 [Unittest] Mark a test target glob
  src/Tests/index.ts
Labels: 1 approval

#758 [Toolchain] Rename command names
  package.json
  src/extension.ts
Labels: 2 approvals

#759 [CfgEditor] Rename command names
  package.json
  src/Config/ConfigStatusBar.ts
  src/extension.ts
Labels: 2 approvals

#763 [Backend] Rename commands
  package.json
  src/extension.ts
Labels: 2 approvals

#762 [Device] Rename commands
  package.json
  src/extension.ts
Labels: 2 approvals

#766 [Viewer] Rename commands
  package.json
  src/extension.ts
Labels: 2 approvals

#771 [Toolchain] Change install button icon
  package.json
Labels: 1 approval

#776 [CfgEditor] Remove unused codes and comments
  media/CfgEditor/cfgeditor.js
  src/CfgEditor/CfgEditorPanel.ts
Labels: 1 approval

#778 [PartEditor] Comment of UI init sequence
  media/PartEditor/index.js
Labels: 1 approval

#777 [PartEditor] Set backend code in Operators listbox
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 2 approvals

#782 [PartEditor] Revise default backend array
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#783 [PartEditor] Handle Backend combobox change
  media/PartEditor/index.js
Labels: 2 approvals

#784 [PartEditor] Update GUI for text edit changes
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 2 approvals

#786 [PartEditor] Two make section helpers
  media/PartEditor/index.js
Labels: 2 approvals

#785 [PartEditor] Introduce makeDefaultPartiton method
  src/PartEditor/PartEditor.ts
Labels: 2 approvals

#787 [PartEditor] Handle default check with update document
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 2 approvals

#789 [CircleGraphCtrl] Revise clearSelection method
  media/CircleGraph/view.js
Labels: 1 approval

#791 [CircleGraphCtrl] Introduce load finish handler
  media/CircleGraph/index.js
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#792 [CircleGraphCtrl] Revise initGraphCtrl to accept model path
  src/CircleGraph/CircleGraph.ts
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#788 [PartEditor] Enable Set button action
  media/PartEditor/index.js
Labels: 2 approvals

#794 [CircleGraphCtrl] Introduce state
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#795 [CircleGraphCtrl] Revise scope for getWebviewOptions
  src/CircleGraph/CircleGraph.ts
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#796 [PartEditor] Enable Clear button action
  media/PartEditor/index.js
Labels: 1 approval

#797 [PartEditor] Handle Set with graph view button
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#798 [CircleGraphCtrl] Introduce CircleGraphEvent
  src/CircleGraph/CircleGraph.ts
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#801 [PartEditor] Select nodes on graph view load
  media/CircleGraph/index.js
  media/CircleGraph/view.js
  src/CircleGraph/CircleGraphCtrl.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#802 [CircleGraphCtrl] Notify selection change
  media/CircleGraph/index.js
  media/CircleGraph/view.js
  src/CircleGraph/CircleGraphCtrl.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#803 [PartEditor] More commands for PartGraphSelector
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#804 [PartEditor] Update document from GraphSelector
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#806 [PartEditor] Close PartGraphSelector
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#807 [CircleGraph] Tidy unnecessary semicolon
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#805 [PartEditor] Update PartGraphSelector with Backend change
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#767 [OneExplorer] Use TreeView API
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals, GIF

#809 [PartEditor] Tidy console log
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#819 [CircleGraph] Introduce initial view mode
  media/CircleGraph/index.html
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#825 [PartEditor] USe TRIX
  media/PartEditor/index.html
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#826 [PartEditor] Set view mode to selector
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#827 [CircleGraph] Introduce host view mode
  media/CircleGraph/index.js
Labels: 1 approval

#829 [CircleGraph] Apply condition for selector view mode
  media/CircleGraph/index.js
  media/CircleGraph/view.js
Labels: 1 approval

#833 [CircleGraph] Revive features of viewer mode
  media/CircleGraph/index.js
  media/CircleGraph/view.js
Labels: 1 approval

#836 [CircleViewer] Initial version of circle viewer
  package.json
  src/CircleGraph/CircleViewer.ts
  src/extension.ts
Labels: 2 approvals

#845 [CircleViewer] Move view owner to document
  src/CircleGraph/CircleViewer.ts
Labels: 1 approval

#844 [CircleViewer] Disable MultipleEditorsPerDocument
  src/CircleGraph/CircleViewer.ts
Labels: 1 approval

#846 [CircleViewer] Enable Multiview per document
  src/CircleGraph/CircleViewer.ts
Labels: 1 approval

#847 [CircleGraph] Remove old graph viewer
  package.json
  src/extension.ts
Labels: 1 approval

#857 [CfgEditor] Remove deprecated codes
  media/CfgEditor/cfgeditor.css
  media/CfgEditor/cfgeditor.js
Labels: 1 approval

#855 [OneExplorer] Hide from command palette
  package.json
Labels: 2 approvals

#861 [PartEditor] Revise to use becode
  media/PartEditor/index.js
Labels: 1 approval

#864 [CircleGraph] Tidy 'about' style
  media/CircleGraph/index.html
Labels: 1 approval

#865 [PartEditor] Use color by backend
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#867 [CircleGraphCtrl] Introduce disposed state
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#868 [CircleGraph] View files for modification
  media/CircleGraph/view-grapher.css
  media/CircleGraph/view-grapher.js
  media/CircleGraph/view-sidebar.css
  media/CircleGraph/view-sidebar.js
Labels: 1 approval

#869 [CirclrGraphCtrl] Enable system theme change
  media/CircleGraph/index.js
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#871 [CircleGraphCtrl] Apply vscode-dark theme class
  media/CircleGraph/view.js
Labels: 1 approval

#872 [CircleGraphCtrl] Revise style to follow vscode
  media/CircleGraph/index.html
  media/CircleGraph/view-grapher.css
  media/CircleGraph/view-sidebar.css
Labels: 1 approval

#875 [CircleGraphCtrl] Apply config theme change
  media/CircleGraph/index.js
  media/CircleGraph/view.js
  src/CircleGraph/CircleGraphCtrl.ts
Labels: 1 approval

#879 [CircleGraph] Change selection line style
  media/CircleGraph/view-grapher.css
Labels: 1 approval

#873 [OneExplorer] Change an info log to debug
  src/OneExplorer/OneExplorer.ts
Labels: 1 approval

#878 [OneExplorer] Separate OneccRunner
  src/OneExplorer/OneExplorer.ts
  src/OneExplorer/OneccRunner.ts
Labels: 2 approvals

#883 [PartEditor] Introduce PartEditor class
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#885 [PartEditor] Revise PartEditorProvider to use PartEditor
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#886 [workflow] Update Release note file position
  .github/workflows/build-release.yml
Labels: 2 approvals

#888 [PartEditor] Tidy unused codes
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#889 Update Release version to 0.2.0
  package-lock.json
  package.json
Labels: 2 approvals

#891 [PartEditor] Revise to hold multiple PartGraphSelPanel with ID
  src/PartEditor/PartEditor.ts
  src/PartEditor/PartGraphSelector.ts
Labels: 1 approval

#892 [PartEditor] Show operator code in operators list
  media/PartEditor/index.js
Labels: 1 approval

#893 [CircleGraph] Add keyCtrl and keyShift
  media/CircleGraph/view.js
Labels: 1 approval

#894 [PartEditor] Event handler for dispose
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#895 [CircleGraph] Use let
  media/CircleGraph/view.js
Labels: 1 approval

#896 [CirclrGraph] set category style only for viewer mode
  media/CircleGraph/view.js
Labels: 1 approval

#897 [CircleGraph] clang format off of get class
  media/CircleGraph/view.js
Labels: 1 approval

#898 [PartEditor] Revise show graph view button
  media/PartEditor/index.html
Labels: 1 approval

#899 [PartEditor] Comments for message from web view
  src/PartEditor/PartEditor.ts
Labels: 1 approval

#901 [CircleGraph] Remove double host
  media/CircleGraph/view.js
Labels: 1 approval

#900 [PartEditor] Revise backend combobox change
  media/PartEditor/index.js
  src/PartEditor/PartEditor.ts
Labels: 1 approval
