Repository Samsung/ONE-vscode, pull requests merged in 2023-10, with the labels that each got.

#1671 [EdgeTPU] Add files for .edgetpucfg
  media/EdgeTPUCfgEditor/cfgeditor.css
  media/EdgeTPUCfgEditor/cfgeditor.html
  media/EdgeTPUCfgEditor/displaycfg.js
  media/EdgeTPUCfgEditor/index.js
  media/EdgeTPUCfgEditor/updateContent.js
  media/EdgeTPUCfgEditor/updateUI.js
  media/EdgeTPUCfgEditor/vscodeapi.js
Labels: Ready for review, SSAFY

#1701 [OneStorage] Revisit constructors
  src/OneExplorer/OneStorage.ts
Labels: 1 approval

#1700 [OneStorage] Deprecate BaseModelToCfgMap
  src/OneExplorer/OneStorage.ts
  src/Tests/OneExplorer/OneStorage.test.ts
Labels: 2 approvals

#1696 [EdgeTPU] Expand createCfg method for other cfg types
  src/CfgEditor/CfgData.ts
  src/CfgEditor/EdgeTPUCfgData.ts
  src/CfgEditor/ICfgData.ts
  src/OneExplorer/OneExplorer.ts
Labels: Ready for review, SSAFY

#1697 [EdgeTPU] Add EdgeTPUCompiler
  src/Backend/CompilerImpl/DebianCompiler.ts
  src/Backend/EdgeTPU/EdgeTPUToolchain.ts
  src/Backend/One/OneToolchain.ts
  src/Tests/Backend/EdgeTPU/EdgeTPUToolchain.test.ts
Labels: Ready for review, SSAFY

#1698 [EdgeTPU] Update Toolchain run notification and log
  src/Toolchain/JobConfig.ts
  src/Toolchain/ToolchainEnv.ts
  src/Toolchain/ToolchainProvider.ts
Labels: Ready for review, SSAFY

#1704 [OneStorage] Improve insert
  src/OneExplorer/OneStorage.ts
Labels: 1 approval

#1708 [OneExplorer] Enhance node map
  src/OneExplorer/OneExplorer.ts
  src/OneExplorer/OneStorage.ts
Labels: 1 approval

#1707 [Test] Fix async test
  src/Tests/MPQEditor/MPQEditor.test.ts
  src/Tests/Utils/Hash.test.ts
  src/Utils/Hash.ts
Labels: 1 approval

#1709 [EdgeTPU] Add EdgeTPUToolchain
  src/Backend/EdgeTPU/EdgeTPUToolchain.ts
  src/Tests/Backend/EdgeTPU/EdgeTPUToolchain.test.ts
Labels: SSAFY

#1714 [Test] Alter mocha timeout
  src/Tests/index.ts
Labels: 1 approval

#1711 [MPQEditor] Fix createDefaultMPQ
  src/MPQEditor/MPQEditor.ts
Labels: 1 approval

#1715 [ONEToolchain] Rename prerequisites script
  script/prerequisitesForGetOneToolchain.sh
  src/Tests/Backend/One/OneToolchain.test.ts
Labels: SSAFY

#1716 [EdgeTPU] Add EdgeTPU backend registration codes
  src/Backend/API.ts
  src/Tests/Backend/Backend.test.ts
  src/Tests/Toolchain/ToolchainProvider.test.ts
  src/Tests/View/InstallQuickInput.test.ts
  src/extension.ts
Labels: SSAFY

#1710 [OneExplorer] Targeted refresh on Change/Delete
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/OneExplorer.ts
  src/OneExplorer/OneStorage.ts
Labels: 2 approvals

#1720 [release/0.5.0] Update dependency package version
  .eslintrc.json
  infra/license/license-judgment.json
  package-lock.json
  package.json
Labels: 1 approval
