Repository Samsung/ONE-vscode, pull requests merged in 2023-09, with the labels that each got.

#1618 [Extension] Revisit recommendation
  .vscode/extensions.json
Labels: 1 approval

#1610 [Logger] Add redact step
  src/Utils/Logger.ts
Labels: 2 approvals

#1619 [Action] Remove clang-format-8 installation
  .github/workflows/check-pr-format.yml
Labels: 2 approvals

#1631 [API] Clarify APIs
  src/Backend/API.ts
  src/Tests/Backend/Backend.test.ts
  src/extension.ts
Labels: 2 approvals

#1620 [CircleEditor] Clean dead codes
  media/CircleEditor/view.js
Labels: 1 approval

#1635 [API] Set context of backend enabled
  src/Backend/API.ts
Labels: 2 approvals

#1636 [Backend] Remove executors
  src/Backend/API.ts
  src/Tests/Backend/Backend.test.ts
Labels: 2 approvals

#1642 [ahub/sam] Exclude test code
  .ahub/sam/exclude.txt
Labels: 2 approvals

#1645 [JsonTracer] Deprecate JsonTracer
  package.json
  src/OneExplorer/ConfigObject.ts
Labels: 2 approvals

#1646 [Toolchain] Update command title
  package.json
Labels: 2 approvals

#1644 [Test] Remove meaningless assertions
  src/Tests/Toolchain/ToolchainEnv.test.ts
  src/Tests/Toolchain/ToolchainProvider.test.ts
  src/Tests/Utils/PipedSpawnSync.test.ts
Labels: 2 approvals

#1641 [OneExplorer] Relieve function complexity
  src/Tests/OneExplorer/ConfigObject.test.ts
Labels: 2 approvals

#1647 [OneExplorer] Open files with default editor
  src/OneExplorer/ConfigObject.ts
Labels: 2 approvals

#1650 [Execute] Expand node entries at HostPC parent node
  src/Execute/DeviceViewProvider.ts
Labels: 1 approval

#1648 [MPQEditor] Add create menu from OneExplorer
  package.json
  src/MPQEditor/MPQEditor.ts
Labels: 2 approvals

#1666 [ONEToolchain] Rename prerequisites script
  script/prerequisitesForGetOneToolchain.sh
  src/Backend/One/OneToolchain.ts
  src/Tests/Backend/One/OneToolchain.test.ts
Labels: SSAFY

#1663 [Toolchain] Update toolchain icon
  src/Toolchain/ToolchainProvider.ts
Labels: 1 approval

#1665 [Toolchain] Refresh device view when default toolchain is changed
  src/Toolchain/DefaultToolchain.ts
  src/Toolchain/ToolchainProvider.ts
Labels: 1 approval

#1669 [EdgeTPU] Extract Interface for Modularization (CfgData)
  src/CfgEditor/CfgData.ts
  src/CfgEditor/ICfgData.ts
Labels: SSAFY

#1667 [EdgeTPU] Add shell script for the prerequisites
  script/prerequisitesForGetEdgeTPUToolchain.sh
Labels: SSAFY

#1654 [OneExplorer] Activate keybindings with condition
  package.json
Labels: 2 approvals

#1674 [Toolchain] Show detailed error messages in run()
  src/Toolchain/ToolchainProvider.ts
Labels: 2 approvals

#1660 [Execute] Introduce SimulatorDevice and TargetDevice
  src/Execute/Device.ts
  src/Tests/Execute/Device.test.ts
Labels: 2 approvals

#1662 [Execute] Introduce DeviceViewNode by device type
  src/Execute/DeviceViewProvider.ts
  src/Tests/Execute/DeviceViewProvider.test.ts
Labels: 2 approvals

#1672 [EdgeTpu] Separate ConfigObject's logic dependent on Backend by introducing ConfigSetting
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/ConfigSetting.ts
  src/OneExplorer/ConfigSettings/OneConfigSetting.ts
  src/Tests/OneExplorer/ConfigObject.test.ts
  src/Tests/OneExplorer/ConfigSetting.test.ts
  src/Tests/OneExplorer/ConfigSettings/OneConfigSettings.test.ts
Labels: SSAFY

#1668 [EdgeTPU] Add EdgeTPUDebianToolchain
  src/Backend/EdgeTPU/EdgeTPUToolchain.ts
  src/Tests/Backend/EdgeTPU/EdgeTPUToolchain.test.ts
Labels: SSAFY

#1664 [OneExplorer] Open tflite and onnx with netron
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1676 [res] Add onnx model
  res/modelDir/truediv/model.onnx
Labels: 1 approval

#1679 [Test] Relocate teardown
  src/Tests/MPQEditor/MPQEditor.test.ts
  src/Tests/OneExplorer/ConfigObject.test.ts
  src/Tests/OneExplorer/OneExplorer.test.ts
  src/Tests/OneExplorer/OneStorage.test.ts
  src/Tests/Utils/Hash.test.ts
Labels: 1 approval

#1661 [Execute] Register SimulatorDevice with Toolchain information
  src/Execute/DeviceViewProvider.ts
  src/Tests/Execute/DeviceViewProvider.test.ts
Labels: 1 approval

#1681 [Execute] Use forEach instead of Map
  src/Execute/DeviceViewProvider.ts
Labels: 1 approval

#1675 [Execute] Update default executor icon
  src/Execute/DeviceViewProvider.ts
Labels: 1 approval

#1680 [workflows] Use boolean type in publish extension workflow
  .github/workflows/publish-extension.yml
Labels: 1 approval

#1683 [Tests] Exclude CircleEditor and MetadataViewer from nyc test files
  src/Tests/index.ts
Labels: 1 approval

#1687 [CircleGraph] Fix constructor
  media/CircleGraph/view-sidebar.js
Labels: 1 approval

#1684 [OneToolchain] Add one toolchain test cases
  src/Tests/Backend/One/OneToolchain.test.ts
Labels: 1 approval

#1673 [EdgeTPU] Implement EdgeTPUCfgData using the ICfgData interface
  src/CfgEditor/CfgData.ts
  src/CfgEditor/EdgeTPUCfgData.ts
  src/CfgEditor/ICfgData.ts
  src/CfgEditor/Sections.ts
  src/Tests/CfgEditor/EdgeTPUCfgData.test.ts
Labels: SSAFY

#1682 [EdgeTpu] Introduce EdgeTpuConfigSetting
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/ConfigSettings/EdgeTpuConfigSetting.ts
  src/Tests/OneExplorer/ConfigObject.test.ts
  src/Tests/OneExplorer/ConfigSettings/EdgeTpuConfigSetting.test.ts
Labels: SSAFY

#1685 [CfgEditor] Check properties existence in loop
  media/CfgEditor/displaycfg.js
  media/CfgEditor/index.js
  media/CfgEditor/updateContent.js
Labels: 1 approval

#1643 [media] Check origin of messages
  media/CfgEditor/index.js
  media/CircleEditor/index.js
  media/CircleGraph/index.js
  media/Jsontracer/index.js
  media/MPQEditor/index.js
  media/MetadataViewer/index.js
  media/Mondrian/mondrianViewer.js
  media/PartEditor/index.js
Labels: 2 approvals

#1688 [MetadataViewer] Hide commands
  package.json
Labels: 1 approval

#1693 [MPQEditor] Hide from menu
  package.json
Labels: 1 approval

#1689 [EdgeTpu] Implements Explorer for EdgeTpu Backend
  src/OneExplorer/OneExplorer.ts
  src/OneExplorer/OneStorage.ts
  src/Tests/OneExplorer/OneExplorer.test.ts
  src/Tests/OneExplorer/OneStorage.test.ts
Labels: SSAFY

#1695 [Infra] Update ONE-vscode version to v0.5.0
  infra/release/release_note.md
  package-lock.json
  package.json
Labels: 1 approval
