Repository Samsung/ONE-vscode, pull requests merged in 2023-01, with the labels that each got.

#1461 [OneExplorer] Fix trivial typos
  src/OneExplorer/ArtifactLocator.ts
  src/OneExplorer/ConfigObject.ts
  src/OneExplorer/OneExplorer.ts
  src/OneExplorer/OneStorage.ts
Labels: 1 approval

#1464 Remove chai from product code
  src/OneExplorer/OneExplorer.ts
  src/OneExplorer/OneStorage.ts
  src/Tests/MockCompiler.ts
Labels: 2 approvals, Quick Fix

#1466 [OneExplorer] Add reveal function
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1467 [OneExplorer] Fix ArtifactLocator
  src/OneExplorer/ArtifactLocator.ts
  src/Tests/OneExplorer/ConfigObject.test.ts
  src/Tests/OneExplorer/OneStorage.test.ts
Labels: 2 approvals, Quick Fix

#1469 [Toolchain] Fix the problem of one toolchain installation failure
  src/Backend/One/OneToolchain.ts
Labels: 1 approval

#1475 [OneExplorer] Fix a unit test
  src/Tests/OneExplorer/OneExplorer.test.ts
  src/Tests/OneExplorer/OneStorage.test.ts
Labels: 2 approvals

#1476 [OneStorage] Fix unit tests
  src/Tests/OneExplorer/OneStorage.test.ts
Labels: 2 approvals

#1477 [ci] Use node16 by default in GitHub Actions
  .github/workflows/build-release.yml
  .github/workflows/check-commit.yml
  .github/workflows/check-copyright.yml
  .github/workflows/check-daily-license.yml
  .github/workflows/check-license.yml
  .github/workflows/check-pr-format.yml
  .github/workflows/check-pr-test.yml
  .github/workflows/check-pr-tsc.yml
  .github/workflows/publish-extension.yml
Labels: 1 approval

#1483 [ci] Change the build-release workflow name
  .github/workflows/official-release.yml
Labels: 1 approval

#1484 [ci] Version up the vscode engine to v1.63.0
  package-lock.json
  package.json
Labels: 1 approval

#1485 Add logo image
  logo/images/logo_original_samsungblue.png
  package.json
Labels: 1 approval
