Repository Samsung/ONE-vscode, pull requests merged in 2023-06, with the labels that each got.

#1568 Introduce stdout result variable in JobRunner
  src/Job/Job.ts
  src/Job/JobRunner.ts
  src/Job/ToolRunner.ts
Labels: 1 approval

#1569 Use a free server number in npm test-no-screen command
  package.json
Labels: 1 approval

#1573 Add result variable to JobCommand
  src/Job/JobCommand.ts
Labels: 1 approval

#1581 [Toolchain] Implement profile in ToolchianProvider
  package.json
  src/Tests/Toolchain/ToolchainProvider.test.ts
  src/Toolchain/ToolchainProvider.ts
Labels: 1 approval

#1582 [Toolchain] Show prerequisites error messages
  src/View/InstallQuickInput.ts
Labels: 1 approval

#1583 [Toolchain] Implement getModelInfo in ToolchainProvider
  package.json
  src/Tests/Toolchain/ToolchainProvider.test.ts
  src/Toolchain/ToolchainProvider.ts
Labels: 1 approval

#1585 [OneExplorer] Append the extname to the contextValue
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1588 [OneExplorer] Fix typo in comment
  src/OneExplorer/OneStorage.ts
Labels: 1 approval

#1589 [OneExplorer] Add delete shortcut
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1593 [OneExplorer] Seperate delete command
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals, Quick Fix

#1594 [Toolchain] Use option in ProfileModel command
  src/Toolchain/ToolchainProvider.ts
Labels: 1 approval

#1592 [OneExplorer] Introduce infer function to product file
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1595 [OneExplorer] Introduce profile functon to product file
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1587 [OneExplorer] Add rename shortcut
  package.json
  src/OneExplorer/OneExplorer.ts
Labels: 2 approvals

#1597 [OneExplorer] Show profile result from profileModel command
  src/OneExplorer/ConfigObject.ts
Labels: 2 approvals
